from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[("auth","0012_alter_user_first_name_max_length")]
    operations=[
        migrations.CreateModel(name="Plan",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=50,unique=True)),("price",models.PositiveIntegerField(default=0)),("resume_limit",models.PositiveIntegerField(default=1)),("interview_limit",models.PositiveIntegerField(default=1))]),
        migrations.CreateModel(name="Job",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=160)),("company",models.CharField(max_length=160)),("location",models.CharField(blank=True,max_length=160)),("remote",models.BooleanField(default=False)),("skills",models.JSONField(blank=True,default=list)),("apply_url",models.URLField(blank=True)),("description",models.TextField(blank=True))]),
        migrations.CreateModel(name="Resume",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("file",models.FileField(upload_to="resumes/")),("extracted_text",models.TextField(blank=True)),("analysis",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="resumes",to="auth.user"))]),
        migrations.CreateModel(name="Subscription",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("started_at",models.DateTimeField(auto_now_add=True)),("expires_at",models.DateTimeField(blank=True,null=True)),("plan",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="api.plan")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,to="auth.user"))]),
        migrations.CreateModel(name="Usage",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("resumes_used",models.PositiveIntegerField(default=0)),("interviews_used",models.PositiveIntegerField(default=0)),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,to="auth.user"))]),
        migrations.CreateModel(name="Interview",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(max_length=120)),("status",models.CharField(default="active",max_length=30)),("questions",models.JSONField(blank=True,default=list)),("answers",models.JSONField(blank=True,default=list)),("scorecard",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("resume",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="api.resume")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="interviews",to="auth.user"))]),
        migrations.CreateModel(name="Payment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("order_id",models.CharField(max_length=160,unique=True)),("payment_id",models.CharField(blank=True,max_length=160)),("signature",models.CharField(blank=True,max_length=300)),("status",models.CharField(default="created",max_length=30)),("created_at",models.DateTimeField(auto_now_add=True)),("plan",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="api.plan")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="auth.user"))])
    ]
